; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32 @ ^6.12.0
board = 4d_systems_esp32s3_gen4_r8n16
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, direct
extra_scripts = pre:fix_rtti.py
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = opi_opi ; This is the "magic" flag for N16R8
board_build.flash_mode = qio              ; Forces Octal Flash mode
board_upload.flash_size = 16MB            ; Corrects the 8MB/16MB mismatch
board_build.f_flash = 80000000L           ; Sets Flash to 80MHz

build_unflags =
    -fno-rtti
    -Werror
    -frtti
build_flags =
    -fexceptions
    -frtti
    -Wno-error
    -D BOARD_HAS_PSRAM
    -D CONFIG_SPIRAM_USE_MALLOC
lib_deps =
    k0i05/esp_mpu6050@^1.2.7

build_type = debug
