//
// Created by Ezra Golombek on 31/01/2026.
//

#ifndef PHISITERPETER_ESP32_ROTATEMOTORBYEXPRESSION_H
#define PHISITERPETER_ESP32_ROTATEMOTORBYEXPRESSION_H


class RotateMotorByExpression {
};


#endif //PHISITERPETER_ESP32_ROTATEMOTORBYEXPRESSION_H